# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 982916c0ca5bb78571f3d8ad5c8168acdf6361b40eca82f967103d8af0f22db4c458511ee9e164d6e85765e7d6b07758a0d13129799c1f872e3d42db7828d3f2

test:
  secret_key_base: 1abca29b7737ae601b9df215637767e548ff2f59550e71ff3990ce4aa4605328e1e69276b941bb629c08134136c0d63329fa00ce9cd16ed8b5af7f7a3e789b2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
